class Flight:
    def __init__(self):
        self.graph = {
   		"ABQ" : ["JFK"],
   		"ACK" : ["BOS","DCA","HPN","JFK","LGA"],
   		"ALB" : ["FLL","MCO"],
   		"ANC" : ["PDX","SEA"],
   		"ANU" : ["JFK"],
   		"ATL" : ["BOS","FLL","JFK","MCO"],
   		"AUA" : ["BOS","FLL","JFK"],
   		"AUS" : ["BOS","FLL","JFK","LGB","MCO"],
   		"BDA" : ["BOS","JFK"],
   		"BDL" : ["DCA","FLL","MCO","PBI","RSW","SJU","TPA"],
   		"BGI" : ["BOS","EWR","FLL","JFK"],
   		"BNA" : ["BOS","FLL"],
   		"BOG" : ["FLL","MCO"],
   		"BOS" : ["ACK","ATL","AUA","AUS","BDA","BGI","BNA","BUF","BUR","BWI","CHS","CLE","CLT","CUN","DCA","DEN","DFW","DTW","EWR","FLL","GCM","HAV","HDN","HOU","IAD","JAX","JFK","LAS","LAX","LGA","LGB","LIR","MBJ","MCO","MEX","MSP","MSY","MVY","NAS","OAK","ORD","PAP","PBI","PDX","PHL","PHX","PIT","PLS","POP","PSP","PUJ","RDU","RIC","ROC","RSW","SAN","SAV","SDQ","SEA","SFO","SJC","SJU","SLC","SMF","SRQ","STI","SYR","TPA","UVF"],
   		"BQN" : ["FLL","JFK","MCO"],
   		"BTV" : ["JFK"],
   		"BUF" : ["BOS","FLL","JFK","LAX","MCO"],
   		"BUR" : ["BOS","JFK"],
   		"BWI" : ["BOS","FLL","MCO"],
   		"BZN" : ["LGB"],
   		"CHS" : ["BOS","DCA","FLL","JFK"],
   		"CLE" : ["BOS","FLL"],
   		"CLT" : ["BOS","JFK"],
   		"CMW" : ["FLL"],
   		"CTG" : ["FLL","JFK"],
   		"CUN" : ["BOS","FLL","JFK","MCO"],
   		"CUR" : ["JFK"],
   		"DAB" : ["JFK"],
   		"DCA" : ["ACK","BDL","BOS","CHS","FLL","JAX","MCO","NAS","PBI","RSW","SJU","TPA"],
   		"DEN" : ["BOS","JFK"],
   		"DFW" : ["BOS"],
   		"DTW" : ["BOS","FLL"],
   		"EWR" : ["BGI","BOS","FLL","MCO","PBI","RSW","SDQ","SJU","STI","TPA"],
   		"FLL" : ["ALB","ATL","AUA","AUS","BDL","BGI","BNA","BOG","BOS","BQN","BUF","BWI","CHS","CLE","CMW","CTG","CUN","DCA","DTW","EWR","GCM","GYE","HAV","HDN","HOG","HPN","JAX","JFK","KIN","LAS","LAX","LGA","LGB","LIM","MBJ","MDE","MEX","MSY","NAS","ORD","ORH","PAP","PHL","PHX","PIT","PLS","POS","PUJ","PVD","RDU","RIC","SAN","SDQ","SFO","SJO","SJU","SLC","SNU","STI","SWF","SXM","SYR","UIO"],
   		"GCM" : ["BOS","FLL","JFK"],
   		"GND" : ["JFK"],
   		"GYE" : ["FLL"],
   		"HAV" : ["BOS","FLL","JFK","MCO"],
   		"HDN" : ["BOS","FLL","LGB"],
   		"HOG" : ["FLL"],
   		"HOU" : ["BOS","JFK"],
   		"HPN" : ["ACK","FLL","MCO","PBI","RSW","TPA"],
   		"HYA" : ["JFK"],
   		"IAD" : ["BOS","JFK"],
   		"JAX" : ["BOS","DCA","FLL","JFK"],
   		"JFK" : ["ABQ","ACK","ANU","ATL","AUA","AUS","BDA","BGI","BOS","BQN","BTV","BUF","BUR","CHS","CLT","CTG","CUN","CUR","DAB","DEN","FLL","GCM","GND","HAV","HOU","HYA","IAD","JAX","KIN","LAS","LAX","LGB","LIR","LRM","MBJ","MCO","MEX","MSY","MVY","NAS","OAK","ONT","ORD","ORH","PAP","PBI","PDX","PHX","PLS","POP","POS","PSE","PSP","PUJ","PWM","RDU","RNO","ROC","RSW","SAN","SAV","SDQ","SEA","SFO","SJC","SJU","SLC","SMF","SRQ","STI","SXM","SYR","TPA","UVF"],
   		"KIN" : ["FLL","JFK"],
   		"LAS" : ["BOS","FLL","JFK","LGB"],
   		"LAX" : ["BOS","BUF","FLL","JFK","MCO"],
   		"LGA" : ["ACK","BOS","FLL","MCO","PBI"],
   		"LGB" : ["AUS","BOS","BZN","FLL","HDN","JFK","LAS","OAK","PDX","RNO","SEA","SFO","SJC","SLC","SMF"],
   		"LIM" : ["FLL"],
   		"LIR" : ["BOS","JFK"],
   		"LRM" : ["JFK"],
   		"MBJ" : ["BOS","FLL","JFK","MCO"],
   		"MCO" : ["ALB","ATL","AUS","BDL","BOG","BOS","BQN","BUF","BWI","CUN","DCA","EWR","HAV","HPN","JFK","LAX","LGA","MBJ","MEX","NAS","ORH","PAP","PSE","PVD","RIC","SDQ","SJO","SJU","SLC","SWF","SYR"],
   		"MDE" : ["FLL"],
   		"MEX" : ["BOS","FLL","JFK","MCO"],
   		"MSP" : ["BOS"],
   		"MSY" : ["BOS","FLL","JFK"],
   		"MVY" : ["BOS","JFK"],
   		"NAS" : ["BOS","DCA","FLL","JFK","MCO"],
   		"OAK" : ["BOS","JFK","LGB"],
   		"ONT" : ["JFK"],
   		"ORD" : ["BOS","FLL","JFK"],
   		"ORH" : ["FLL","JFK","MCO"],
   		"PAP" : ["BOS","FLL","JFK","MCO"],
   		"PBI" : ["BDL","BOS","DCA","EWR","HPN","JFK","LGA","PVD"],
   		"PDX" : ["ANC","BOS","JFK","LGB"],
   		"PHL" : ["BOS","FLL"],
   		"PHX" : ["BOS","FLL","JFK"],
   		"PIT" : ["BOS","FLL"],
   		"PLS" : ["BOS","FLL","JFK"],
   		"POP" : ["BOS","JFK"],
   		"POS" : ["FLL","JFK"],
   		"PSE" : ["JFK","MCO"],
   		"PSP" : ["BOS","JFK"],
   		"PUJ" : ["BOS","FLL","JFK","SJU"],
   		"PVD" : ["FLL","MCO","PBI"],
   		"PWM" : ["JFK"],
   		"RDU" : ["BOS","FLL","JFK"],
   		"RIC" : ["BOS","FLL","MCO"],
   		"RNO" : ["JFK","LGB"],
   		"ROC" : ["BOS","JFK"],
   		"RSW" : ["BDL","BOS","DCA","EWR","HPN","JFK"],
   		"SAN" : ["BOS","FLL","JFK"],
   		"SAV" : ["BOS","JFK"],
   		"SDQ" : ["BOS","EWR","FLL","JFK","MCO","SJU"],
   		"SEA" : ["ANC","BOS","JFK","LGB"],
   		"SFO" : ["BOS","FLL","JFK","LGB"],
   		"SJC" : ["BOS","JFK","LGB"],
   		"SJO" : ["FLL","MCO"],
   		"SJU" : ["BDL","BOS","DCA","EWR","FLL","JFK","MCO","PUJ","SDQ","STI","STT","STX","TPA"],
   		"SLC" : ["BOS","FLL","JFK","LGB","MCO"],
   		"SMF" : ["BOS","JFK","LGB"],
   		"SNU" : ["FLL"],
   		"SRQ" : ["BOS","JFK"],
   		"STI" : ["BOS","EWR","FLL","JFK","SJU"],
   		"STT" : ["SJU"],
   		"STX" : ["SJU"],
   		"SWF" : ["FLL","MCO"],
   		"SXM" : ["FLL","JFK"],
   		"SYR" : ["BOS","FLL","JFK","MCO"],
   		"TPA" : ["BDL","BOS","DCA","EWR","HPN","JFK","SJU"],
   		"UIO" : ["FLL"],
   		"UVF" : ["BOS","JFK"]
    }

        self.edges = [
		["ABQ", "JFK"],
		["ACK", "BOS"],
		["ACK", "DCA"],
		["ACK", "HPN"],
		["ACK", "JFK"],
		["ACK", "LGA"],
		["ALB", "FLL"],
		["ALB", "MCO"],
		["ANC", "PDX"],
		["ANC", "SEA"],
		["ANU", "JFK"],
		["ATL", "BOS"],
		["ATL", "FLL"],
		["ATL", "JFK"],
		["ATL", "MCO"],
		["AUA", "BOS"],
		["AUA", "FLL"],
		["AUA", "JFK"],
		["AUS", "BOS"],
		["AUS", "FLL"],
		["AUS", "JFK"],
		["AUS", "LGB"],
		["AUS", "MCO"],
		["BDA", "BOS"],
		["BDA", "JFK"],
		["BDL", "DCA"],
		["BDL", "FLL"],
		["BDL", "MCO"],
		["BDL", "PBI"],
		["BDL", "RSW"],
		["BDL", "SJU"],
		["BDL", "TPA"],
		["BGI", "BOS"],
		["BGI", "EWR"],
		["BGI", "FLL"],
		["BGI", "JFK"],
		["BNA", "BOS"],
		["BNA", "FLL"],
		["BOG", "FLL"],
		["BOG", "MCO"],
		["BOS", "ACK"],
		["BOS", "ATL"],
		["BOS", "AUA"],
		["BOS", "AUS"],
		["BOS", "BDA"],
		["BOS", "BGI"],
		["BOS", "BNA"],
		["BOS", "BUF"],
		["BOS", "BUR"],
		["BOS", "BWI"],
		["BOS", "CHS"],
		["BOS", "CLE"],
		["BOS", "CLT"],
		["BOS", "CUN"],
		["BOS", "DCA"],
		["BOS", "DEN"],
		["BOS", "DFW"],
		["BOS", "DTW"],
		["BOS", "EWR"],
		["BOS", "FLL"],
		["BOS", "GCM"],
		["BOS", "HAV"],
		["BOS", "HDN"],
		["BOS", "HOU"],
		["BOS", "IAD"],
		["BOS", "JAX"],
		["BOS", "JFK"],
		["BOS", "LAS"],
		["BOS", "LAX"],
		["BOS", "LGA"],
		["BOS", "LGB"],
		["BOS", "LIR"],
		["BOS", "MBJ"],
		["BOS", "MCO"],
		["BOS", "MEX"],
		["BOS", "MSP"],
		["BOS", "MSY"],
		["BOS", "MVY"],
		["BOS", "NAS"],
		["BOS", "OAK"],
		["BOS", "ORD"],
		["BOS", "PAP"],
		["BOS", "PBI"],
		["BOS", "PDX"],
		["BOS", "PHL"],
		["BOS", "PHX"],
		["BOS", "PIT"],
		["BOS", "PLS"],
		["BOS", "POP"],
		["BOS", "PSP"],
		["BOS", "PUJ"],
		["BOS", "RDU"],
		["BOS", "RIC"],
		["BOS", "ROC"],
		["BOS", "RSW"],
		["BOS", "SAN"],
		["BOS", "SAV"],
		["BOS", "SDQ"],
		["BOS", "SEA"],
		["BOS", "SFO"],
		["BOS", "SJC"],
		["BOS", "SJU"],
		["BOS", "SLC"],
		["BOS", "SMF"],
		["BOS", "SRQ"],
		["BOS", "STI"],
		["BOS", "SYR"],
		["BOS", "TPA"],
		["BOS", "UVF"],
		["BQN", "FLL"],
		["BQN", "JFK"],
		["BQN", "MCO"],
		["BTV", "JFK"],
		["BUF", "BOS"],
		["BUF", "FLL"],
		["BUF", "JFK"],
		["BUF", "LAX"],
		["BUF", "MCO"],
		["BUR", "BOS"],
		["BUR", "JFK"],
		["BWI", "BOS"],
		["BWI", "FLL"],
		["BWI", "MCO"],
		["BZN", "LGB"],
		["CHS", "BOS"],
		["CHS", "DCA"],
		["CHS", "FLL"],
		["CHS", "JFK"],
		["CLE", "BOS"],
		["CLE", "FLL"],
		["CLT", "BOS"],
		["CLT", "JFK"],
		["CMW", "FLL"],
		["CTG", "FLL"],
		["CTG", "JFK"],
		["CUN", "BOS"],
		["CUN", "FLL"],
		["CUN", "JFK"],
		["CUN", "MCO"],
		["CUR", "JFK"],
		["DAB", "JFK"],
		["DCA", "ACK"],
		["DCA", "BDL"],
		["DCA", "BOS"],
		["DCA", "CHS"],
		["DCA", "FLL"],
		["DCA", "JAX"],
		["DCA", "MCO"],
		["DCA", "NAS"],
		["DCA", "PBI"],
		["DCA", "RSW"],
		["DCA", "SJU"],
		["DCA", "TPA"],
		["DEN", "BOS"],
		["DEN", "JFK"],
		["DFW", "BOS"],
		["DTW", "BOS"],
		["DTW", "FLL"],
		["EWR", "BGI"],
		["EWR", "BOS"],
		["EWR", "FLL"],
		["EWR", "MCO"],
		["EWR", "PBI"],
		["EWR", "RSW"],
		["EWR", "SDQ"],
		["EWR", "SJU"],
		["EWR", "STI"],
		["EWR", "TPA"],
		["FLL", "ALB"],
		["FLL", "ATL"],
		["FLL", "AUA"],
		["FLL", "AUS"],
		["FLL", "BDL"],
		["FLL", "BGI"],
		["FLL", "BNA"],
		["FLL", "BOG"],
		["FLL", "BOS"],
		["FLL", "BQN"],
		["FLL", "BUF"],
		["FLL", "BWI"],
		["FLL", "CHS"],
		["FLL", "CLE"],
		["FLL", "CMW"],
		["FLL", "CTG"],
		["FLL", "CUN"],
		["FLL", "DCA"],
		["FLL", "DTW"],
		["FLL", "EWR"],
		["FLL", "GCM"],
		["FLL", "GYE"],
		["FLL", "HAV"],
		["FLL", "HDN"],
		["FLL", "HOG"],
		["FLL", "HPN"],
		["FLL", "JAX"],
		["FLL", "JFK"],
		["FLL", "KIN"],
		["FLL", "LAS"],
		["FLL", "LAX"],
		["FLL", "LGA"],
		["FLL", "LGB"],
		["FLL", "LIM"],
		["FLL", "MBJ"],
		["FLL", "MDE"],
		["FLL", "MEX"],
		["FLL", "MSY"],
		["FLL", "NAS"],
		["FLL", "ORD"],
		["FLL", "ORH"],
		["FLL", "PAP"],
		["FLL", "PHL"],
		["FLL", "PHX"],
		["FLL", "PIT"],
		["FLL", "PLS"],
		["FLL", "POS"],
		["FLL", "PUJ"],
		["FLL", "PVD"],
		["FLL", "RDU"],
		["FLL", "RIC"],
		["FLL", "SAN"],
		["FLL", "SDQ"],
		["FLL", "SFO"],
		["FLL", "SJO"],
		["FLL", "SJU"],
		["FLL", "SLC"],
		["FLL", "SNU"],
		["FLL", "STI"],
		["FLL", "SWF"],
		["FLL", "SXM"],
		["FLL", "SYR"],
		["FLL", "UIO"],
		["GCM", "BOS"],
		["GCM", "FLL"],
		["GCM", "JFK"],
		["GND", "JFK"],
		["GYE", "FLL"],
		["HAV", "BOS"],
		["HAV", "FLL"],
		["HAV", "JFK"],
		["HAV", "MCO"],
		["HDN", "BOS"],
		["HDN", "FLL"],
		["HDN", "LGB"],
		["HOG", "FLL"],
		["HOU", "BOS"],
		["HOU", "JFK"],
		["HPN", "ACK"],
		["HPN", "FLL"],
		["HPN", "MCO"],
		["HPN", "PBI"],
		["HPN", "RSW"],
		["HPN", "TPA"],
		["HYA", "JFK"],
		["IAD", "BOS"],
		["IAD", "JFK"],
		["JAX", "BOS"],
		["JAX", "DCA"],
		["JAX", "FLL"],
		["JAX", "JFK"],
		["JFK", "ABQ"],
		["JFK", "ACK"],
		["JFK", "ANU"],
		["JFK", "ATL"],
		["JFK", "AUA"],
		["JFK", "AUS"],
		["JFK", "BDA"],
		["JFK", "BGI"],
		["JFK", "BOS"],
		["JFK", "BQN"],
		["JFK", "BTV"],
		["JFK", "BUF"],
		["JFK", "BUR"],
		["JFK", "CHS"],
		["JFK", "CLT"],
		["JFK", "CTG"],
		["JFK", "CUN"],
		["JFK", "CUR"],
		["JFK", "DAB"],
		["JFK", "DEN"],
		["JFK", "FLL"],
		["JFK", "GCM"],
		["JFK", "GND"],
		["JFK", "HAV"],
		["JFK", "HOU"],
		["JFK", "HYA"],
		["JFK", "IAD"],
		["JFK", "JAX"],
		["JFK", "KIN"],
		["JFK", "LAS"],
		["JFK", "LAX"],
		["JFK", "LGB"],
		["JFK", "LIR"],
		["JFK", "LRM"],
		["JFK", "MBJ"],
		["JFK", "MCO"],
		["JFK", "MEX"],
		["JFK", "MSY"],
		["JFK", "MVY"],
		["JFK", "NAS"],
		["JFK", "OAK"],
		["JFK", "ONT"],
		["JFK", "ORD"],
		["JFK", "ORH"],
		["JFK", "PAP"],
		["JFK", "PBI"],
		["JFK", "PDX"],
		["JFK", "PHX"],
		["JFK", "PLS"],
		["JFK", "POP"],
		["JFK", "POS"],
		["JFK", "PSE"],
		["JFK", "PSP"],
		["JFK", "PUJ"],
		["JFK", "PWM"],
		["JFK", "RDU"],
		["JFK", "RNO"],
		["JFK", "ROC"],
		["JFK", "RSW"],
		["JFK", "SAN"],
		["JFK", "SAV"],
		["JFK", "SDQ"],
		["JFK", "SEA"],
		["JFK", "SFO"],
		["JFK", "SJC"],
		["JFK", "SJU"],
		["JFK", "SLC"],
		["JFK", "SMF"],
		["JFK", "SRQ"],
		["JFK", "STI"],
		["JFK", "SXM"],
		["JFK", "SYR"],
		["JFK", "TPA"],
		["JFK", "UVF"],
		["KIN", "FLL"],
		["KIN", "JFK"],
		["LAS", "BOS"],
		["LAS", "FLL"],
		["LAS", "JFK"],
		["LAS", "LGB"],
		["LAX", "BOS"],
		["LAX", "BUF"],
		["LAX", "FLL"],
		["LAX", "JFK"],
		["LAX", "MCO"],
		["LGA", "ACK"],
		["LGA", "BOS"],
		["LGA", "FLL"],
		["LGA", "MCO"],
		["LGA", "PBI"],
		["LGB", "AUS"],
		["LGB", "BOS"],
		["LGB", "BZN"],
		["LGB", "FLL"],
		["LGB", "HDN"],
		["LGB", "JFK"],
		["LGB", "LAS"],
		["LGB", "OAK"],
		["LGB", "PDX"],
		["LGB", "RNO"],
		["LGB", "SEA"],
		["LGB", "SFO"],
		["LGB", "SJC"],
		["LGB", "SLC"],
		["LGB", "SMF"],
		["LIM", "FLL"],
		["LIR", "BOS"],
		["LIR", "JFK"],
		["LRM", "JFK"],
		["MBJ", "BOS"],
		["MBJ", "FLL"],
		["MBJ", "JFK"],
		["MBJ", "MCO"],
		["MCO", "ALB"],
		["MCO", "ATL"],
		["MCO", "AUS"],
		["MCO", "BDL"],
		["MCO", "BOG"],
		["MCO", "BOS"],
		["MCO", "BQN"],
		["MCO", "BUF"],
		["MCO", "BWI"],
		["MCO", "CUN"],
		["MCO", "DCA"],
		["MCO", "EWR"],
		["MCO", "HAV"],
		["MCO", "HPN"],
		["MCO", "JFK"],
		["MCO", "LAX"],
		["MCO", "LGA"],
		["MCO", "MBJ"],
		["MCO", "MEX"],
		["MCO", "NAS"],
		["MCO", "ORH"],
		["MCO", "PAP"],
		["MCO", "PSE"],
		["MCO", "PVD"],
		["MCO", "RIC"],
		["MCO", "SDQ"],
		["MCO", "SJO"],
		["MCO", "SJU"],
		["MCO", "SLC"],
		["MCO", "SWF"],
		["MCO", "SYR"],
		["MDE", "FLL"],
		["MEX", "BOS"],
		["MEX", "FLL"],
		["MEX", "JFK"],
		["MEX", "MCO"],
		["MSP", "BOS"],
		["MSY", "BOS"],
		["MSY", "FLL"],
		["MSY", "JFK"],
		["MVY", "BOS"],
		["MVY", "JFK"],
		["NAS", "BOS"],
		["NAS", "DCA"],
		["NAS", "FLL"],
		["NAS", "JFK"],
		["NAS", "MCO"],
		["OAK", "BOS"],
		["OAK", "JFK"],
		["OAK", "LGB"],
		["ONT", "JFK"],
		["ORD", "BOS"],
		["ORD", "FLL"],
		["ORD", "JFK"],
		["ORH", "FLL"],
		["ORH", "JFK"],
		["ORH", "MCO"],
		["PAP", "BOS"],
		["PAP", "FLL"],
		["PAP", "JFK"],
		["PAP", "MCO"],
		["PBI", "BDL"],
		["PBI", "BOS"],
		["PBI", "DCA"],
		["PBI", "EWR"],
		["PBI", "HPN"],
		["PBI", "JFK"],
		["PBI", "LGA"],
		["PBI", "PVD"],
		["PDX", "ANC"],
		["PDX", "BOS"],
		["PDX", "JFK"],
		["PDX", "LGB"],
		["PHL", "BOS"],
		["PHL", "FLL"],
		["PHX", "BOS"],
		["PHX", "FLL"],
		["PHX", "JFK"],
		["PIT", "BOS"],
		["PIT", "FLL"],
		["PLS", "BOS"],
		["PLS", "FLL"],
		["PLS", "JFK"],
		["POP", "BOS"],
		["POP", "JFK"],
		["POS", "FLL"],
		["POS", "JFK"],
		["PSE", "JFK"],
		["PSE", "MCO"],
		["PSP", "BOS"],
		["PSP", "JFK"],
		["PUJ", "BOS"],
		["PUJ", "FLL"],
		["PUJ", "JFK"],
		["PUJ", "SJU"],
		["PVD", "FLL"],
		["PVD", "MCO"],
		["PVD", "PBI"],
		["PWM", "JFK"],
		["RDU", "BOS"],
		["RDU", "FLL"],
		["RDU", "JFK"],
		["RIC", "BOS"],
		["RIC", "FLL"],
		["RIC", "MCO"],
		["RNO", "JFK"],
		["RNO", "LGB"],
		["ROC", "BOS"],
		["ROC", "JFK"],
		["RSW", "BDL"],
		["RSW", "BOS"],
		["RSW", "DCA"],
		["RSW", "EWR"],
		["RSW", "HPN"],
		["RSW", "JFK"],
		["SAN", "BOS"],
		["SAN", "FLL"],
		["SAN", "JFK"],
		["SAV", "BOS"],
		["SAV", "JFK"],
		["SDQ", "BOS"],
		["SDQ", "EWR"],
		["SDQ", "FLL"],
		["SDQ", "JFK"],
		["SDQ", "MCO"],
		["SDQ", "SJU"],
		["SEA", "ANC"],
		["SEA", "BOS"],
		["SEA", "JFK"],
		["SEA", "LGB"],
		["SFO", "BOS"],
		["SFO", "FLL"],
		["SFO", "JFK"],
		["SFO", "LGB"],
		["SJC", "BOS"],
		["SJC", "JFK"],
		["SJC", "LGB"],
		["SJO", "FLL"],
		["SJO", "MCO"],
		["SJU", "BDL"],
		["SJU", "BOS"],
		["SJU", "DCA"],
		["SJU", "EWR"],
		["SJU", "FLL"],
		["SJU", "JFK"],
		["SJU", "MCO"],
		["SJU", "PUJ"],
		["SJU", "SDQ"],
		["SJU", "STI"],
		["SJU", "STT"],
		["SJU", "STX"],
		["SJU", "TPA"],
		["SLC", "BOS"],
		["SLC", "FLL"],
		["SLC", "JFK"],
		["SLC", "LGB"],
		["SLC", "MCO"],
		["SMF", "BOS"],
		["SMF", "JFK"],
		["SMF", "LGB"],
		["SNU", "FLL"],
		["SRQ", "BOS"],
		["SRQ", "JFK"],
		["STI", "BOS"],
		["STI", "EWR"],
		["STI", "FLL"],
		["STI", "JFK"],
		["STI", "SJU"],
		["STT", "SJU"],
		["STX", "SJU"],
		["SWF", "FLL"],
		["SWF", "MCO"],
		["SXM", "FLL"],
		["SXM", "JFK"],
		["SYR", "BOS"],
		["SYR", "FLL"],
		["SYR", "JFK"],
		["SYR", "MCO"],
		["TPA", "BDL"],
		["TPA", "BOS"],
		["TPA", "DCA"],
		["TPA", "EWR"],
		["TPA", "HPN"],
		["TPA", "JFK"],
		["TPA", "SJU"],
		["UIO", "FLL"],
		["UVF", "BOS"],
		["UVF", "JFK"]]